/** FlowGuard Calm Operations Console: ForgeVI’s mission and team are presented as accountable project context, not a marketing profile. */
import { ArrowRight, BadgeCheck, CircleDot, Compass, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";
import { Button } from "@/components/ui/button";

const team = [
  { name: "Aditya Sam", role: "Team leader", initials: "AS", tone: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300" },
  { name: "Arpit Tagade", role: "Team member", initials: "AT", tone: "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300" },
  { name: "Rohan Kodane", role: "Team member", initials: "RK", tone: "bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300" },
  { name: "Atharva Andhare", role: "Team member", initials: "AA", tone: "bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300" },
];

const commitments = [
  { icon: ShieldCheck, title: "Make uncertainty visible", text: "A workflow should never hide an unresolved payment, reservation, or human decision behind a misleading success state." },
  { icon: Compass, title: "Preserve the next safe action", text: "People need clear evidence of what has happened, who owns the decision, and which recovery path is authorized." },
  { icon: BadgeCheck, title: "Build evidence, not promises", text: "The prototype is intentionally narrow, tested under failure conditions, and ready to defend in a technical review." },
];

export default function About() {
  return <AppShell><PageHeader eyebrow="ABOUT FORGEVI" title="We make uncertain work visible, recoverable, and accountable." description="ForgeVI built FlowGuard for teams that coordinate business work across independent systems but still need an authorized human decision at the right moment." action={<Button asChild variant="outline" className="border-slate-200 dark:border-slate-700"><Link href="/tour">Explore the judge tour <ArrowRight className="ml-2 size-3.5" /></Link></Button>} />
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,0.04)] dark:border-slate-700 dark:shadow-black/15"><div className="grid lg:grid-cols-[1.05fr_0.95fr]"><div className="p-6 sm:p-8"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600 dark:text-blue-300">OUR MISSION</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-[-0.055em] text-slate-900 dark:text-slate-100">Bring control back to business processes when systems disagree.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-500 dark:text-slate-400">FlowGuard is ForgeVI’s human-in-the-loop coordination prototype. It preserves durable workflow state, pauses safely for a real decision, and surfaces the recovery path when an external participant fails or returns an uncertain outcome.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><p className="font-mono text-xl font-bold text-blue-600 dark:text-blue-300">01</p><p className="mt-2 text-xs font-bold text-slate-800 dark:text-slate-100">Persist state</p><p className="mt-1 text-[11px] leading-5 text-slate-500 dark:text-slate-400">Keep the evidence durable.</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><p className="font-mono text-xl font-bold text-amber-600 dark:text-amber-300">02</p><p className="mt-2 text-xs font-bold text-slate-800 dark:text-slate-100">Wait safely</p><p className="mt-1 text-[11px] leading-5 text-slate-500 dark:text-slate-400">Make human ownership clear.</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800"><p className="font-mono text-xl font-bold text-emerald-600 dark:text-emerald-300">03</p><p className="mt-2 text-xs font-bold text-slate-800 dark:text-slate-100">Recover clearly</p><p className="mt-1 text-[11px] leading-5 text-slate-500 dark:text-slate-400">Protect business consistency.</p></div></div></div><div className="relative flex min-h-[290px] flex-col justify-end overflow-hidden bg-slate-950 p-7 text-white"><div className="absolute inset-0 login-grid opacity-45" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_24%,rgba(53,106,230,0.34),transparent_31%),radial-gradient(circle_at_20%_78%,rgba(16,185,129,0.16),transparent_29%)]" /><div className="relative"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-200">FORGEVI PRINCIPLE</p><p className="mt-3 max-w-md text-2xl font-extrabold leading-tight tracking-[-0.045em]">“A decision is only safe when the history and consequence are visible.”</p><div className="mt-6 flex items-center gap-2 text-xs text-slate-300"><CircleDot className="size-4 text-emerald-300" />Four builders. One durable coordination system.</div></div></div></div></section>
    <section className="mt-5"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600 dark:text-blue-300">THE TEAM</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.045em] text-slate-900 dark:text-slate-100">ForgeVI</h2></div><UsersRound className="size-6 text-slate-300 dark:text-slate-600" /></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{team.map(member => <article key={member.name} className="fg-interactive rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.03)] hover:-translate-y-0.5 hover:shadow-[0_12px_34px_rgba(15,23,42,0.08)] dark:border-slate-700 dark:shadow-black/10"><div className={`flex size-11 items-center justify-center rounded-xl text-sm font-extrabold ${member.tone}`}>{member.initials}</div><h3 className="mt-5 text-sm font-bold text-slate-900 dark:text-slate-100">{member.name}</h3><p className="mt-1 text-xs font-semibold text-slate-500 dark:text-slate-400">{member.role}</p>{member.role === "Team leader" && <p className="mt-4 inline-flex items-center gap-1.5 rounded-md bg-blue-50 px-2 py-1 text-[10px] font-bold tracking-[0.08em] text-blue-700 dark:bg-blue-500/10 dark:text-blue-300"><BadgeCheck className="size-3" />PROJECT LEAD</p>}</article>)}</div></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-3">{commitments.map(item => <article key={item.title} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700"><div className="flex size-9 items-center justify-center rounded-xl bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"><item.icon className="size-4" /></div><h3 className="mt-4 text-sm font-bold text-slate-800 dark:text-slate-100">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{item.text}</p></article>)}</section>
  </AppShell>;
}
