/** FlowGuard Calm Operations Console: a decision inbox that names downstream consequences before the approver acts. */
import { useEffect, useState } from "react";
import { Check, Clock3, MessageSquareText, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";
import { StatusBadge } from "@/components/flowguard/StatusBadge";
import { useAuth } from "@/contexts/AuthContext";
import { flowguardApi, type ApprovalTask } from "@/lib/flowguard-api";
import { toast } from "sonner";

const due = (value: string) => { const minutes = Math.max(0, Math.ceil((new Date(value).getTime() - Date.now()) / 60_000)); return minutes ? `${minutes} min remaining` : "Deadline passed"; };

export default function Approvals() {
  const { auth } = useAuth(); const [tasks, setTasks] = useState<ApprovalTask[]>([]); const [comments, setComments] = useState<Record<string, string>>({}); const [loadingId, setLoadingId] = useState("");
  const load = async () => { if (!auth) return; try { setTasks(await flowguardApi.approvals(auth.token)); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load approvals."); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 5_000); return () => clearInterval(timer); }, [auth]);
  const decide = async (task: ApprovalTask, decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES") => { if (!auth) return; setLoadingId(`${task.id}:${decision}`); try { await flowguardApi.decide(auth.token, task.id, decision, comments[task.id]); toast.success(decision === "APPROVE" ? "Workflow will continue to payment capture." : decision === "REJECT" ? "Recovery sequence has started." : "Changes request has started a safe return path."); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Decision could not be recorded."); } finally { setLoadingId(""); } };
  return <AppShell><PageHeader eyebrow="HUMAN CHECKPOINTS" title="Make the decision. Keep the record." description="Approval is a durable workflow state. Every decision is authorized on the server, time-stamped, and recorded with its consequences." />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="space-y-4">{tasks.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><Check className="mx-auto size-7 text-emerald-500" /><h2 className="mt-4 text-lg font-bold text-slate-800">Approval inbox is clear</h2><p className="mt-2 text-sm text-slate-500">A purchase request will appear here after payment authorization.</p></div> : tasks.map(task => <article key={task.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-base font-extrabold tracking-[-0.025em] text-slate-900">Purchase approval</p><StatusBadge status={task.status} /></div><p className="mt-2 font-mono text-xs text-slate-500">{task.executionId}</p></div><div className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800"><Clock3 className="mr-1.5 inline size-3.5" />{due(task.dueAt)}</div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-700">Decision consequence</p><p className="mt-1 text-sm leading-6 text-slate-600">Approving continues to payment capture and invoicing. Rejecting begins compensation: void authorization, release inventory, and cancel the CRM order.</p></div><div className="mt-4"><label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-bold text-slate-700"><MessageSquareText className="size-3.5" />Decision note</span><textarea value={comments[task.id] ?? ""} onChange={event => setComments(current => ({ ...current, [task.id]: event.target.value }))} placeholder="Add a concise reason for the audit trail…" className="min-h-20 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none ring-blue-500 transition-shadow focus:ring-2" /></label></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => decide(task, "APPROVE")} disabled={task.status !== "OPEN" || Boolean(loadingId)} className="bg-emerald-600 hover:bg-emerald-700"><Check className="mr-2 size-4" />Approve</Button><Button onClick={() => decide(task, "REJECT")} disabled={task.status !== "OPEN" || Boolean(loadingId)} variant="outline" className="border-rose-200 text-rose-700 hover:bg-rose-50"><X className="mr-2 size-4" />Reject & recover</Button><Button onClick={() => decide(task, "REQUEST_CHANGES")} disabled={task.status !== "OPEN" || Boolean(loadingId)} variant="ghost" className="text-amber-700 hover:bg-amber-50">Request changes</Button></div></article>)}</section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/EsdwdNpdPxtPMEHi.png" alt="Human decision point illustration" className="h-36 w-full rounded-xl object-cover" /><p className="mt-5 text-[10px] font-bold tracking-[0.15em] text-blue-600">WHY THIS MATTERS</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.035em] text-slate-900">A human wait must not break the workflow.</h2><p className="mt-3 text-sm leading-6 text-slate-500">FlowGuard persists the decision task, owner, deadline, and business context. The worker can restart without losing the approval checkpoint.</p></aside></div>
  </AppShell>;
}
