/** FlowGuard Calm Operations Console: a technically honest product explanation supporting the team’s architecture defense at judging time. */
import { Activity, ArrowDown, Database, ServerCog, ShieldCheck, UserRoundCheck } from "lucide-react";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";

const mechanisms = [
  { icon: Database, title: "Durable state in MongoDB", text: "Executions, steps, approvals, jobs, and events are persisted before the coordinator moves forward." },
  { icon: Activity, title: "Atomic job claiming", text: "A Render worker claims one due job using an atomic update and a short lease to recover from a worker crash." },
  { icon: ShieldCheck, title: "Idempotent participant calls", text: "Every side effect has a stable key. A retry returns the recorded result instead of creating duplicate orders, reservations, or charges." },
  { icon: UserRoundCheck, title: "Human wait state", text: "Approval is stored as a task with an owner and deadline. It survives refreshes, redeploys, and worker restarts." },
];

export default function Architecture() {
  return <AppShell><PageHeader eyebrow="SYSTEM DESIGN" title="A focused prototype of the hard problem." description="The project intentionally builds a narrow, measurable slice: durable coordination of a purchase request across machine participants and a human approval checkpoint." />
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="grid lg:grid-cols-[1.05fr_0.95fr]"><div className="p-6 sm:p-8"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600">DEPLOYMENT TOPOLOGY</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.045em] text-slate-900">Separated by responsibility, connected by durable state.</h2><div className="mt-7 space-y-2"><div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-bold text-blue-900">Vercel · React operations console</p><p className="mt-1 text-xs leading-5 text-blue-700">Displays work, accepts human decisions, and calls only the protected API.</p></div><div className="mx-auto flex w-5 justify-center text-slate-300"><ArrowDown className="size-4" /></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold text-slate-900">Render Web Service · Node.js API</p><p className="mt-1 text-xs leading-5 text-slate-600">Authenticates users, creates durable workflow commands, records decisions, and exposes evidence.</p></div><div className="mx-auto flex w-5 justify-center text-slate-300"><ArrowDown className="size-4" /></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-bold text-emerald-900">MongoDB Atlas</p><p className="mt-1 text-xs leading-5 text-emerald-700">State, audit events, jobs, leases, users, idempotency records.</p></div><div className="rounded-xl border border-violet-100 bg-violet-50 p-4"><p className="text-xs font-bold text-violet-900">Render Background Worker</p><p className="mt-1 text-xs leading-5 text-violet-700">Claims jobs, retries failures, checks deadlines, and compensates partial work.</p></div></div></div></div><div className="relative min-h-[260px] overflow-hidden bg-slate-900"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/movpUEJGouzKEKjU.png" alt="Abstract distributed workflow mesh" className="absolute inset-0 size-full object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/75 via-slate-950/15 to-transparent" /><div className="absolute bottom-7 left-7 right-7"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-200">TECHNICAL CLAIM</p><p className="mt-2 text-xl font-extrabold tracking-[-0.04em] text-white">A persisted job ledger plus idempotent participants makes the workflow recoverable after expected failures.</p></div></div></div></section>
    <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{mechanisms.map(item => <div key={item.title} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex size-9 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><item.icon className="size-4" /></div><h3 className="mt-4 text-sm font-bold text-slate-800">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{item.text}</p></div>)}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600">VALIDATION EXPERIMENT</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.04em] text-slate-900">Can the system safely finish a business path after imperfect conditions?</h2><p className="mt-3 text-sm leading-6 text-slate-500">The tests and live controls validate approval waiting, duplicate start prevention, a temporary participant failure, rejection compensation, and event history preservation.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600">INTENTIONAL LIMIT</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.04em] text-slate-900">A credible prototype, not an overbuilt platform.</h2><p className="mt-3 text-sm leading-6 text-slate-500">The MVP uses deterministic adapters instead of real payment and CRM accounts. Production needs connector reconciliation, observability, access controls, backup policy, and a high-throughput queue.</p></div></section>
  </AppShell>;
}
