/** FlowGuard Calm Operations Console: a durable evidence view with a visible event pulse and clear recovery controls. */
import { useEffect, useState } from "react";
import { ArrowLeft, CircleAlert, Copy, LoaderCircle, RotateCcw, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/flowguard/AppShell";
import { StatusBadge } from "@/components/flowguard/StatusBadge";
import { WorkflowPulse } from "@/components/flowguard/WorkflowPulse";
import { useAuth } from "@/contexts/AuthContext";
import { flowguardApi, type ExecutionDetail as Detail } from "@/lib/flowguard-api";
import { toast } from "sonner";

const formatDate = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(value));
const eventLabel = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase());

export default function ExecutionDetail() {
  const [, params] = useRoute("/executions/:id"); const { auth } = useAuth(); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [cancelling, setCancelling] = useState(false);
  const load = async () => { if (!auth || !params?.id) return; try { setDetail(await flowguardApi.execution(auth.token, params.id)); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load execution evidence."); } finally { setLoading(false); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 3_000); return () => clearInterval(timer); }, [auth, params?.id]);
  const cancel = async () => { if (!auth || !detail) return; setCancelling(true); try { await flowguardApi.cancel(auth.token, detail.execution.id); toast.success("Compensation has been started."); await load(); } catch (cancelError) { toast.error(cancelError instanceof Error ? cancelError.message : "Could not start compensation."); } finally { setCancelling(false); } };
  const copy = (value: string) => { navigator.clipboard.writeText(value).then(() => toast.success("Copied to clipboard.")); };
  if (loading) return <AppShell><div className="flex min-h-[60vh] items-center justify-center text-sm text-slate-500"><LoaderCircle className="mr-2 size-4 animate-spin" />Loading durable workflow state…</div></AppShell>;
  if (error || !detail) return <AppShell><Link href="/workspace" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600"><ArrowLeft className="size-4" />Back to control room</Link><div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-6"><CircleAlert className="size-5 text-rose-600" /><p className="mt-3 font-bold text-rose-900">The execution could not be loaded.</p><p className="mt-1 text-sm text-rose-700">{error}</p></div></AppShell>;
  const { execution, steps, events, approval } = detail; const canCancel = ["RUNNING", "WAITING_FOR_APPROVAL"].includes(execution.status);
  return <AppShell><Link href="/workspace" className="inline-flex items-center gap-2 text-xs font-bold text-slate-500 transition-colors hover:text-blue-600"><ArrowLeft className="size-3.5" />Control room</Link><div className="mt-5 flex flex-col gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs text-slate-500">{execution.businessKey}</p><StatusBadge status={execution.status} /></div><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.055em] text-slate-900">Purchase request evidence</h1><p className="mt-2 text-sm text-slate-500">Every transition is durable, time-stamped, and correlated to this single business process.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => copy(execution.correlationId)}><Copy className="mr-2 size-3.5" />Copy correlation ID</Button>{canCancel && <Button onClick={cancel} disabled={cancelling} variant="outline" className="border-rose-200 text-rose-700 hover:bg-rose-50">{cancelling ? <LoaderCircle className="mr-2 size-3.5 animate-spin" /> : <RotateCcw className="mr-2 size-4" />}Cancel & compensate</Button>}</div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-slate-800">Workflow pulse</p><p className="mt-1 text-xs text-slate-500">Forward actions, human wait state, and compensation are all visible here.</p></div><span className="font-mono text-[10px] text-slate-400">{execution.correlationId}</span></div><div className="mt-5"><WorkflowPulse steps={steps} /></div></section><aside className="space-y-5"><div className="rounded-2xl bg-slate-900 p-5 text-white"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-300">CURRENT CONTEXT</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-400">Requester</p><p className="mt-1 font-bold">{execution.input.requester}</p></div><div><p className="text-xs text-slate-400">Total</p><p className="mt-1 font-bold">{new Intl.NumberFormat("en", { style: "currency", currency: execution.input.currency }).format(execution.input.amount)}</p></div><div><p className="text-xs text-slate-400">Product</p><p className="mt-1 font-bold">{execution.input.quantity} × {execution.input.sku}</p></div><div><p className="text-xs text-slate-400">Started</p><p className="mt-1 text-xs font-semibold">{formatDate(execution.startedAt)}</p></div></div>{approval && <div className="mt-5 rounded-xl bg-white/10 p-3"><p className="text-xs font-bold text-amber-200">Approval checkpoint</p><p className="mt-1 text-xs leading-5 text-slate-200">{approval.status === "OPEN" ? `Waiting until ${formatDate(approval.dueAt)}` : `${approval.status.replaceAll("_", " ")} · ${approval.comment || "No comment"}`}</p></div>}</div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-emerald-600" /><p className="text-sm font-bold text-slate-800">Correctness signals</p></div><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-600"><li><span className="font-bold text-slate-800">Idempotency:</span> each service call has a stable operation key.</li><li><span className="font-bold text-slate-800">Worker lease:</span> stalled jobs can be safely reclaimed.</li><li><span className="font-bold text-slate-800">Compensation:</span> completed actions reverse in business-safe order.</li></ul></div></aside></div>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="border-b border-slate-100 px-5 py-4"><p className="text-sm font-bold text-slate-800">Immutable event history</p><p className="mt-1 text-xs text-slate-500">This sequence is the auditable evidence of what the coordinator observed and decided.</p></div><div className="divide-y divide-slate-100">{events.map(event => <div key={event.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[120px_minmax(0,1fr)_150px]"><p className="font-mono text-[10px] text-slate-400">#{String(event.sequence).padStart(2, "0")}</p><div><p className="text-xs font-bold text-slate-800">{eventLabel(event.type)}</p><p className="mt-1 text-xs text-slate-500">{event.stepKey?.replaceAll("-", " ") ?? "workflow"}{event.payload ? ` · ${Object.entries(event.payload).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}` : ""}</p></div><p className="text-xs text-slate-400 sm:text-right">{formatDate(event.createdAt)}</p></div>)}</div></section>
  </AppShell>;
}
