/** FlowGuard Calm Operations Console: the control room makes operational state, ownership, and next action readable in seconds. */
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, CircleAlert, Clock3, ListChecks, PlayCircle, RotateCcw } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";
import { StatusBadge } from "@/components/flowguard/StatusBadge";
import { useAuth } from "@/contexts/AuthContext";
import { flowguardApi, type ApprovalTask, type WorkflowExecution } from "@/lib/flowguard-api";

const formatter = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const formatDate = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

function Metric({ label, value, note, tone }: { label: string; value: number; note: string; tone: "blue" | "amber" | "rose" | "slate" }) {
  const tones = { blue: "bg-blue-50 text-blue-700", amber: "bg-amber-50 text-amber-700", rose: "bg-rose-50 text-rose-700", slate: "bg-slate-100 text-slate-700" };
  return <div className="rounded-2xl border border-slate-200/90 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="flex items-start justify-between"><p className="text-xs font-bold text-slate-500">{label}</p><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${tones[tone]}`}>{note}</span></div><p className="mt-5 text-3xl font-extrabold tracking-[-0.055em] text-slate-900">{value}</p></div>;
}

function EmptyState() { return <div className="flex min-h-[280px] flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><div className="flex size-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><PlayCircle className="size-5" /></div><h2 className="mt-4 text-base font-bold text-slate-800">No workflows are moving yet</h2><p className="mt-1 max-w-xs text-sm leading-6 text-slate-500">Start the purchase-request demo to see durable state, approval waiting, and recovery behavior.</p><Button asChild className="mt-5 bg-blue-600 hover:bg-blue-700"><Link href="/new">Start demo workflow <ArrowRight className="ml-2 size-4" /></Link></Button></div>; }

export default function Home() {
  const { auth } = useAuth();
  const [executions, setExecutions] = useState<WorkflowExecution[]>([]);
  const [approvals, setApprovals] = useState<ApprovalTask[]>([]);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [error, setError] = useState("");
  const load = async () => { if (!auth) return; try { const data = await flowguardApi.dashboard(auth.token); setExecutions(data.recentExecutions); setApprovals(data.openApprovals); setCounts(data.counts); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load the control room."); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 4_000); return () => clearInterval(timer); }, [auth]);
  const attention = (counts.WAITING_FOR_APPROVAL ?? 0) + (counts.MANUAL_RECOVERY_REQUIRED ?? 0) + (counts.COMPENSATING ?? 0);
  const waitingForApproval = counts.WAITING_FOR_APPROVAL ?? 0;
  const running = counts.RUNNING ?? 0;
  const canApprove = auth?.user.role === "ADMIN" || auth?.user.role === "APPROVER";
  return <AppShell><PageHeader eyebrow="CONTROL ROOM" title="Operational clarity for every uncertain workflow." description="See what has succeeded, what is waiting for a human, and what needs recovery before the business process loses momentum." action={<Button asChild className="bg-blue-600 font-bold hover:bg-blue-700"><Link href="/new">Start workflow <ArrowRight className="ml-2 size-4" /></Link></Button>} />
    {error && <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><strong>Connection note:</strong> {error}</div>}
    {waitingForApproval > 0 ? <section className="mb-5 flex flex-col gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><ListChecks className="size-4" /></div><div><p className="text-sm font-bold text-amber-950">{waitingForApproval} workflow{waitingForApproval === 1 ? " is" : "s are"} ready for a human decision.</p><p className="mt-1 text-xs leading-5 text-amber-800">Payment authorization has completed. {canApprove ? "As an authorized user, you can now approve or reject it from the inbox." : "An administrator or approver must decide it from the inbox."}</p></div></div><Button asChild className="bg-amber-600 hover:bg-amber-700"><Link href="/approvals">{canApprove ? "Open approval inbox" : "View approval status"}<ArrowRight className="ml-2 size-4" /></Link></Button></section> : running > 0 ? <section className="mb-5 flex items-start gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-5"><div className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-blue-100 text-blue-700"><Clock3 className="size-4" /></div><div><p className="text-sm font-bold text-blue-950">The workflow is still progressing through system participants.</p><p className="mt-1 text-xs leading-5 text-blue-800">An approval task is created automatically after CRM, inventory, and payment authorization complete. It will then appear in <strong>Approval inbox</strong>, where an administrator or approver can make the decision.</p></div></section> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active workflows" value={(counts.RUNNING ?? 0) + (counts.WAITING_FOR_APPROVAL ?? 0)} note="live" tone="blue" /><Metric label="Human decisions" value={counts.WAITING_FOR_APPROVAL ?? 0} note="waiting" tone="amber" /><Metric label="In recovery" value={(counts.COMPENSATING ?? 0) + (counts.MANUAL_RECOVERY_REQUIRED ?? 0)} note="attention" tone="rose" /><Metric label="Safely resolved" value={(counts.COMPLETED ?? 0) + (counts.COMPENSATED ?? 0)} note="complete" tone="slate" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="rounded-2xl border border-slate-200/90 bg-white shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-sm font-bold text-slate-800">Workflow activity</p><p className="mt-0.5 text-xs text-slate-500">A durable record across every participant.</p></div><Link href="/new" className="text-xs font-bold text-blue-600 hover:text-blue-800">New request</Link></div>{executions.length === 0 ? <EmptyState /> : <div className="divide-y divide-slate-100">{executions.map(execution => <Link key={execution.id} href={`/executions/${execution.id}`} className="group flex items-center gap-4 px-5 py-4 no-underline transition-colors hover:bg-slate-50"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 font-mono text-xs font-bold text-slate-600">{execution.businessKey.slice(-3)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-slate-800">{execution.businessKey}</p><StatusBadge status={execution.status} /></div><p className="mt-1 truncate text-xs text-slate-500">{execution.input.quantity} × {execution.input.sku} · {formatter.format(execution.input.amount)} · currently at {execution.currentStepKey.replaceAll("-", " ")}</p></div><div className="hidden text-right sm:block"><p className="text-xs font-semibold text-slate-600">{formatDate(execution.updatedAt)}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{execution.correlationId}</p></div><ArrowRight className="size-4 text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-blue-600" /></Link>)}</div>}</div>
      <aside className="space-y-5"><div className="overflow-hidden rounded-2xl bg-slate-900 p-5 text-white shadow-[0_12px_34px_rgba(15,23,42,0.18)]"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-300">NEXT SAFE ACTION</p><p className="mt-3 text-2xl font-extrabold tracking-[-0.045em]">{waitingForApproval ? "A decision is ready." : attention ? `${attention} workflow${attention === 1 ? "" : "s"} needs attention.` : running ? "Approval comes next." : "All workflow paths are clear."}</p><p className="mt-3 text-sm leading-6 text-slate-300">{waitingForApproval ? (canApprove ? "Open the inbox to approve, reject, or request changes. Every decision becomes durable evidence." : "An administrator or approver must decide the request from the inbox.") : attention ? "Review the inbox or recovery center before an approval window closes." : running ? "The coordinator is completing system steps. It creates a durable approval task immediately after payment authorization." : "Start a controlled fault scenario to validate retries and compensation."}</p><Button asChild variant="secondary" className="mt-5 bg-white text-slate-900 hover:bg-slate-100"><Link href={waitingForApproval ? "/approvals" : "/new"}>{waitingForApproval ? (canApprove ? "Approve or reject" : "View approval status") : "Start a scenario"}<ArrowRight className="ml-2 size-4" /></Link></Button></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><ListChecks className="size-4 text-amber-600" /><p className="text-sm font-bold text-slate-800">Approval queue</p></div>{approvals.length ? <div className="mt-4 space-y-3">{approvals.slice(0, 3).map(task => <Link href="/approvals" key={task.id} className="block rounded-xl bg-amber-50 p-3 no-underline transition-transform hover:-translate-y-0.5"><p className="font-mono text-[10px] text-amber-700">{task.executionId}</p><p className="mt-1 text-xs font-bold text-amber-950">Decision due {formatDate(task.dueAt)}</p></Link>)}</div> : <p className="mt-4 text-sm leading-6 text-slate-500">No approvals are waiting. The coordinator will create one after payment authorization.</p>}</div></aside></section>
    <section className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><CheckCircle2 className="size-4 text-emerald-600" /><p className="mt-3 text-sm font-bold text-slate-800">Durable evidence</p><p className="mt-1 text-xs leading-5 text-slate-500">Every transition is appended to the event history with time, actor, and outcome.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><Clock3 className="size-4 text-amber-600" /><p className="mt-3 text-sm font-bold text-slate-800">Human checkpoint</p><p className="mt-1 text-xs leading-5 text-slate-500">Approval is a persisted wait state—not a fragile open request.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><RotateCcw className="size-4 text-violet-600" /><p className="mt-3 text-sm font-bold text-slate-800">Safe recovery</p><p className="mt-1 text-xs leading-5 text-slate-500">Rejected or failed requests move through ordered compensation steps.</p></div></section>
  </AppShell>;
}
