/** FlowGuard Calm Operations Console: an interactive, judge-ready walkthrough that converts system behavior into a repeatable live demonstration. */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, FlaskConical, RotateCcw, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";

const tourSteps = [
  { kicker: "01 / ARM A CONTROLLED FAILURE", title: "Prove that a retry does not repeat the business action.", detail: "Open the workflow launcher and select Inventory fails once. FlowGuard stores the job, observes one temporary error, and creates a delayed retry with the same participant idempotency key.", evidence: ["STEP_RETRY_SCHEDULED event", "Same idempotency key", "No duplicate reservation"], icon: FlaskConical, action: "Open workflow launcher", href: "/new", tone: "bg-blue-50 text-blue-700" },
  { kicker: "02 / HOLD FOR HUMAN JUDGMENT", title: "Show that an approval is a durable wait—not an open browser request.", detail: "After payment authorization, sign in as manager@flowguard.demo. The approval inbox shows the assigned owner, deadline, and business consequence before the person decides.", evidence: ["Persistent approval task", "Assigned approver + deadline", "Server-enforced decision"], icon: ShieldCheck, action: "Open approval inbox", href: "/approvals", tone: "bg-amber-50 text-amber-700" },
  { kicker: "03 / REJECT AND RECOVER", title: "Make the compensation sequence visible.", detail: "Reject the request. The coordinator records the decision, then reverses eligible completed work in business-safe order: void payment authorization, release inventory, and cancel the CRM order.", evidence: ["COMPENSATION_STARTED", "Reverse business order", "COMPENSATED outcome"], icon: RotateCcw, action: "Open recovery center", href: "/recovery", tone: "bg-violet-50 text-violet-700" },
  { kicker: "04 / DEFEND WITH EVIDENCE", title: "Close with measurable reliability outcomes.", detail: "Open analytics to distinguish completed workflows, safely compensated workflows, and truly manual exceptions. This is the operational evidence behind the design claim.", evidence: ["Completion rate", "Safe recovery rate", "Manual exceptions remain visible"], icon: CheckCircle2, action: "Open reliability analytics", href: "/analytics", tone: "bg-emerald-50 text-emerald-700" },
];

export default function JudgeTour() {
  const [stepIndex, setStepIndex] = useState(0); const [, navigate] = useLocation(); const step = tourSteps[stepIndex]; const Icon = step.icon; const progress = useMemo(() => `${Math.round(((stepIndex + 1) / tourSteps.length) * 100)}%`, [stepIndex]);
  return <AppShell><PageHeader eyebrow="JUDGE TOUR" title="A six-minute story of failure, human judgment, and safe recovery." description="This guide is interactive by design: each stage points to the exact workspace screen and the evidence judges should observe before moving on." action={<Button asChild variant="outline"><Link href="/workspace"><ArrowLeft className="mr-2 size-3.5" />Control room</Link></Button>} />
    <div className="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)_320px]"><aside className="rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><p className="px-3 pb-3 pt-2 text-[10px] font-bold tracking-[0.15em] text-slate-400">WALKTHROUGH PROGRESS</p>{tourSteps.map((item, index) => <button onClick={() => setStepIndex(index)} key={item.kicker} className={`mb-1 w-full rounded-xl p-3 text-left transition-all ${index === stepIndex ? "bg-blue-50 text-blue-800 shadow-sm" : "text-slate-600 hover:bg-slate-50"}`}><div className="flex items-center gap-2"><span className={`flex size-6 items-center justify-center rounded-lg text-[10px] font-bold ${index === stepIndex ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-500"}`}>{index + 1}</span><span className="text-xs font-bold">{item.title.split(" ").slice(0, 4).join(" ")}…</span></div></button>)}<div className="mx-3 mt-5 border-t border-slate-100 pt-4"><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-all duration-300" style={{ width: progress }} /></div><p className="mt-2 text-[11px] font-semibold text-slate-500">Step {stepIndex + 1} of {tourSteps.length}</p></div></aside>
      <section className="relative overflow-hidden rounded-2xl bg-slate-900 p-6 text-white shadow-[0_14px_38px_rgba(15,23,42,0.2)] sm:p-9"><div className="absolute -right-28 -top-28 size-72 rounded-full bg-blue-500/20 blur-3xl" /><div className="relative"><div className={`flex size-12 items-center justify-center rounded-2xl ${step.tone}`}><Icon className="size-6" /></div><p className="mt-7 text-[10px] font-bold tracking-[0.18em] text-blue-300">{step.kicker}</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-[-0.055em] sm:text-4xl">{step.title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-300">{step.detail}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{step.evidence.map(item => <div key={item} className="rounded-xl border border-white/10 bg-white/[0.06] p-3"><CircleAlert className="size-4 text-blue-300" /><p className="mt-3 text-xs font-bold text-white">{item}</p></div>)}</div><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => navigate(step.href)} className="bg-white text-slate-900 hover:bg-slate-100">{step.action}<ArrowRight className="ml-2 size-4" /></Button>{stepIndex > 0 && <Button onClick={() => setStepIndex(index => index - 1)} variant="ghost" className="text-white hover:bg-white/10 hover:text-white">Previous stage</Button>}{stepIndex < tourSteps.length - 1 && <Button onClick={() => setStepIndex(index => index + 1)} variant="ghost" className="text-blue-200 hover:bg-white/10 hover:text-white">Read next stage</Button>}</div></div></section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-600">PRESENTATION TIP</p><h3 className="mt-3 text-lg font-extrabold tracking-[-0.04em] text-slate-900">Narrate the evidence, not just the screens.</h3><p className="mt-3 text-sm leading-6 text-slate-500">At every stop, state the failure condition, the persisted record, the guardrail that prevents duplicate action, and the next safe state.</p><div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-800">Suggested final line</p><p className="mt-2 text-xs leading-5 text-slate-600">“FlowGuard does not assume that a system or a person responds perfectly. It records uncertainty and gives the business a safe next step.”</p></div></aside></div>
  </AppShell>;
}
