/** FlowGuard Calm Operations Console: a focused workflow launcher that names each simulation consequence instead of hiding demo mechanics. */
import { useState } from "react";
import { ArrowRight, FlaskConical, LoaderCircle, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";
import { useAuth } from "@/contexts/AuthContext";
import { flowguardApi } from "@/lib/flowguard-api";
import { toast } from "sonner";

const faults = [
  { participant: "inventory" as const, mode: "FAIL_ONCE" as const, label: "Inventory fails once", description: "The worker retries a temporary reservation failure." },
  { participant: "payment" as const, mode: "UNKNOWN_ONCE" as const, label: "Payment loses its response", description: "The next try reconciles using the same idempotency key." },
  { participant: "invoice" as const, mode: "FAIL_ONCE" as const, label: "Invoice fails once", description: "The worker schedules a safe retry before compensation." },
];

export default function NewWorkflow() {
  const { auth } = useAuth(); const [, navigate] = useLocation();
  const [form, setForm] = useState({ businessKey: `ORDER-${Math.floor(1000 + Math.random() * 8000)}`, requester: "Priya Shah", sku: "SKU-42", quantity: 2, amount: 500, currency: "USD", reason: "Department equipment" });
  const [fault, setFault] = useState<typeof faults[number] | null>(null); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof form, value: string | number) => setForm(current => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!auth) return; setLoading(true); try { if (fault) await flowguardApi.setFault(auth.token, fault.participant, fault.mode); const execution = await flowguardApi.start(auth.token, { businessKey: form.businessKey, idempotencyKey: `ui:${crypto.randomUUID()}`, input: { requester: form.requester, sku: form.sku, quantity: Number(form.quantity), amount: Number(form.amount), currency: form.currency, reason: form.reason } }); const firstSubmissionKey = `flowguard:first-submission:${auth.user.id}`; const isFirstSubmission = !window.localStorage.getItem(firstSubmissionKey); if (isFirstSubmission) window.localStorage.setItem(firstSubmissionKey, "true"); toast.success(isFirstSubmission ? "Your first workflow is safely underway." : fault ? `${fault.label} is armed.` : "Workflow safely started.", isFirstSubmission ? { description: "Follow the durable timeline to see each system step and the approval handoff." } : undefined); navigate(`/executions/${execution.id}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to start workflow."); } finally { setLoading(false); } };
  return <AppShell><PageHeader eyebrow="WORKFLOW LAUNCHER" title="Start a purchase request with controlled conditions." description="The API creates a durable execution record first. The background worker then claims each participant action from MongoDB." />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><ArrowRight className="size-5" /></div><div><p className="text-sm font-bold text-slate-800">Request context</p><p className="text-xs text-slate-500">This becomes the immutable business input for the workflow.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="mb-2 block text-xs font-bold text-slate-700">Business key</span><Input value={form.businessKey} onChange={event => update("businessKey", event.target.value)} className="h-11" /></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-700">Requester</span><Input value={form.requester} onChange={event => update("requester", event.target.value)} className="h-11" /></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-700">Product SKU</span><Input value={form.sku} onChange={event => update("sku", event.target.value)} className="h-11" /></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-700">Quantity</span><Input type="number" min={1} value={form.quantity} onChange={event => update("quantity", Number(event.target.value))} className="h-11" /></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-700">Amount (USD)</span><Input type="number" min={1} value={form.amount} onChange={event => update("amount", Number(event.target.value))} className="h-11" /></label><label className="block sm:col-span-2"><span className="mb-2 block text-xs font-bold text-slate-700">Business reason</span><Input value={form.reason} onChange={event => update("reason", event.target.value)} className="h-11" /></label></div><div className="mt-7 flex flex-wrap items-center gap-3"><Button disabled={loading} className="h-11 bg-blue-600 px-5 font-bold hover:bg-blue-700">{loading ? <><LoaderCircle className="mr-2 size-4 animate-spin" />Creating durable record…</> : <>Start workflow <ArrowRight className="ml-2 size-4" /></>}</Button><span className="text-xs text-slate-500">A manager approval will be created after payment authorization.</span></div></form>
      <aside className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="relative overflow-hidden bg-slate-900 p-5 text-white"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/BuwJwwEgnAcHwIlQ.png" alt="FlowGuard recovery visual" className="absolute inset-0 size-full object-cover opacity-30" /><div className="relative"><p className="text-[10px] font-bold tracking-[0.15em] text-blue-300">LIVE EVALUATION</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.04em]">Arm a controlled fault</h2><p className="mt-2 text-sm leading-6 text-slate-300">Make the resilience mechanism visible without relying on a real outage.</p></div></div><div className="p-4">{faults.map(item => <button type="button" key={item.label} onClick={() => setFault(fault?.label === item.label ? null : item)} className={`mb-2 w-full rounded-xl border p-3 text-left transition-all ${fault?.label === item.label ? "border-blue-500 bg-blue-50 shadow-sm" : "border-slate-200 hover:border-slate-300 hover:bg-slate-50"}`}><div className="flex items-center gap-2"><FlaskConical className={`size-4 ${fault?.label === item.label ? "text-blue-600" : "text-slate-400"}`} /><p className="text-xs font-bold text-slate-800">{item.label}</p></div><p className="mt-1 pl-6 text-[11px] leading-4 text-slate-500">{item.description}</p></button>)}<div className="mt-4 flex gap-2 rounded-xl bg-emerald-50 p-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-emerald-600" /><p className="text-[11px] leading-5 text-emerald-800">These scenarios are deterministic and recorded in the event stream for the judging demo.</p></div></div></aside></div>
  </AppShell>;
}
