/** FlowGuard Calm Operations Console: a public product page that frames durable coordination as practical enterprise infrastructure, not decorative marketing. */
import { ArrowRight, CheckCircle2, CirclePlay, Clock3, Database, Moon, RefreshCw, ShieldCheck, Sun, UserRound } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";

const productVisuals = {
  hero: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/ylvMjedTRTWKhKyq.png",
  approval: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/gInYbjDzTcsBZTQh.png",
  recovery: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/mlnCZLcVOKclaqDK.png",
};

const benefits = [
  { icon: Database, title: "Durable by default", text: "Every request, participant step, decision, and recovery action is saved as a durable workflow record." },
  { icon: UserRound, title: "Human decisions at the right moment", text: "Workflow execution pauses safely where business judgment is required instead of hiding uncertainty behind automation." },
  { icon: RefreshCw, title: "Recovery you can explain", text: "Retries, compensation, and manual recovery keep partial failures visible and give teams a clear next safe action." },
];

const useCases = [
  { title: "Purchase requests", text: "Coordinate inventory, payment, approval, and fulfilment without losing the record of what has already happened." },
  { title: "Customer operations", text: "Guide service changes across CRM, billing, and notifications while keeping a human owner accountable for exceptions." },
  { title: "Business exceptions", text: "Turn failed downstream calls into a visible recovery path rather than an invisible support ticket or uncertain record." },
];

function WorkflowPulseRail() {
  const stages = [
    { label: "REQUEST RECORDED", detail: "ORDER-1042", tone: "bg-blue-500", note: "09:42" },
    { label: "DECISION DUE", detail: "Owner: Asha", tone: "bg-amber-400", note: "10:05" },
    { label: "SAFE RECOVERY", detail: "Audit retained", tone: "bg-emerald-500", note: "10:11" },
  ];
  return <div className="mt-9 max-w-xl border-t border-slate-200 pt-5 dark:border-slate-800"><div className="relative grid grid-cols-3 gap-3">{stages.map((stage, index) => <div key={stage.label} className="relative"><span className={`mb-2 flex size-3 rounded-full ${stage.tone} ring-4 ring-[#F6F8FC] dark:ring-slate-950`} />{index < stages.length - 1 && <span className="absolute left-3 top-1.5 h-px w-[calc(100%-0.75rem)] bg-slate-300 dark:bg-slate-700" />}<p className="font-mono text-[9px] font-bold tracking-[0.08em] text-slate-500 dark:text-slate-400">{stage.note}</p><p className="mt-1 text-[10px] font-extrabold tracking-[0.08em] text-slate-700 dark:text-slate-200">{stage.label}</p><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400">{stage.detail}</p></div>)}</div></div>;
}

export default function Product() {
  const { theme, toggleTheme } = useTheme();
  return <main className="min-h-svh bg-[#F6F8FC] text-slate-900 dark:bg-slate-950 dark:text-slate-100"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-[#F6F8FC]/90 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/90"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3 no-underline"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663889343004/TJucKfGMGLCqWyAe.png" alt="FlowGuard" className="size-10 rounded-xl shadow-sm" /><span><span className="block text-base font-extrabold tracking-[-0.04em] text-slate-900 dark:text-slate-100">FlowGuard</span><span className="block text-[9px] font-bold tracking-[0.14em] text-slate-400">FORGEVI</span></span></Link><nav className="hidden items-center gap-6 text-xs font-bold text-slate-500 lg:flex"><a href="#how-it-works" className="transition-colors hover:text-blue-600 dark:hover:text-blue-300">How it works</a><a href="#benefits" className="transition-colors hover:text-blue-600 dark:hover:text-blue-300">Benefits</a><a href="#real-world" className="transition-colors hover:text-blue-600 dark:hover:text-blue-300">Use cases</a></nav><div className="flex items-center gap-2"><Button onClick={toggleTheme} variant="ghost" size="icon" className="fg-interactive text-slate-500 dark:text-slate-300" aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}>{theme === "dark" ? <Sun className="size-4" /> : <Moon className="size-4" />}</Button><Button asChild variant="outline" className="hidden border-slate-200 bg-white text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 sm:inline-flex"><a href="/login">Sign in</a></Button></div></div></header>
    <section className="relative overflow-hidden"><div className="absolute inset-x-0 top-0 h-[520px] bg-[radial-gradient(circle_at_82%_2%,rgba(53,106,230,0.15),transparent_31%),radial-gradient(circle_at_18%_32%,rgba(16,185,129,0.07),transparent_24%)]" /><div className="relative mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-16 lg:grid-cols-[0.93fr_1.07fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div><p className="text-[11px] font-bold tracking-[0.17em] text-blue-600 dark:text-blue-300">HUMAN-IN-THE-LOOP WORKFLOW COORDINATION</p><h1 className="mt-5 max-w-2xl text-5xl font-extrabold leading-[0.98] tracking-[-0.065em] text-slate-950 dark:text-white sm:text-6xl">When systems disagree, <span className="text-blue-600 dark:text-blue-300">FlowGuard</span> keeps work moving safely.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300">FlowGuard coordinates business workflows across inventory, payments, approvals, and recovery. It makes every decision visible, every handoff accountable, and every failure recoverable.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 bg-blue-600 px-6 font-bold hover:bg-blue-700"><a href="/login" aria-label="Get Started: enter the decision workspace">Get Started <ArrowRight className="ml-2 size-4" /></a></Button><Button asChild size="lg" variant="outline" className="h-12 border-slate-300 bg-white px-6 font-bold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"><a href="/login?demo=1" aria-label="Get a Demo: enter the prepared decision workspace"><CirclePlay className="mr-2 size-4 text-blue-600 dark:text-blue-300" />Get a Demo</a></Button></div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Enter a clean decision workspace, or review a prepared recoverable workflow with the evidence already in place.</p><WorkflowPulseRail /></div><div className="relative"><div className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 p-2 shadow-[0_28px_80px_rgba(15,23,42,0.22)]"><img src={productVisuals.hero} alt="Abstract durable workflow coordination across business systems" className="aspect-[16/10] w-full rounded-[19px] object-cover" /></div><div className="absolute -bottom-5 -left-3 max-w-[245px] rounded-2xl border border-slate-200 bg-white p-4 shadow-xl dark:border-slate-700 dark:bg-slate-900 sm:-left-8"><p className="font-mono text-[10px] font-bold tracking-[0.12em] text-slate-400">CORR-7F2B · ORDER-1042</p><p className="mt-2 text-sm font-extrabold text-slate-900 dark:text-slate-100">Decision due before capture.</p><p className="mt-2 flex items-center gap-1.5 text-[11px] leading-4 text-slate-500 dark:text-slate-400"><span className="size-1.5 rounded-full bg-amber-400" />Owner: Asha · Approval window open</p></div></div></div></section>
    <section id="how-it-works" className="border-y border-slate-200 bg-white py-16 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-[10px] font-bold tracking-[0.16em] text-blue-600 dark:text-blue-300">HOW FLOWGUARD WORKS</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.05em] text-slate-900 dark:text-slate-100">A reliable path through multi-system business work.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ number: "01", title: "Capture the request", text: "Start with business context, a stable identity, and a durable record before any downstream action happens." }, { number: "02", title: "Coordinate and pause", text: "FlowGuard completes safe system steps, then waits for an authorized person when business judgment matters." }, { number: "03", title: "Complete or recover", text: "The product records the outcome, retries temporary faults, and compensates safely if the workflow cannot continue." }].map(item => <article key={item.number} className="rounded-2xl border border-slate-200 bg-[#F9FAFC] p-6 dark:border-slate-700 dark:bg-slate-800"><p className="font-mono text-sm font-bold text-blue-600 dark:text-blue-300">{item.number}</p><h3 className="mt-5 text-base font-bold text-slate-800 dark:text-slate-100">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{item.text}</p></article>)}</div></div></section>
    <section id="benefits" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-8"><div className="relative overflow-hidden rounded-3xl border border-slate-200 bg-slate-100 dark:border-slate-700 dark:bg-slate-800"><img src={productVisuals.approval} alt="Business manager reviewing a workflow decision" className="aspect-[4/3] w-full object-cover" /><div className="absolute bottom-4 left-4 right-4 rounded-xl border border-white/20 bg-slate-950/85 p-3 text-white backdrop-blur"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-300">ORDER-1042 · 10:05</span><span className="rounded-md bg-amber-300/15 px-2 py-1 text-[9px] font-bold tracking-[0.08em] text-amber-200">APPROVAL OPEN</span></div><p className="mt-2 text-xs font-bold">Owner: Asha · Capture payment is blocked until a decision is recorded.</p></div></div><div><p className="text-[10px] font-bold tracking-[0.16em] text-blue-600 dark:text-blue-300">WHY TEAMS USE IT</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.05em] text-slate-900 dark:text-slate-100">Automation without losing human accountability.</h2><div className="mt-7 space-y-5">{benefits.map(item => <div key={item.title} className="flex gap-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300"><item.icon className="size-4" /></span><div><h3 className="text-sm font-bold text-slate-800 dark:text-slate-100">{item.title}</h3><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">{item.text}</p></div></div>)}</div></div></section>
    <section id="real-world" className="border-y border-slate-200 bg-white py-20 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-8"><div><p className="text-[10px] font-bold tracking-[0.16em] text-blue-600 dark:text-blue-300">REAL-WORLD VALUE</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.05em] text-slate-900 dark:text-slate-100">A practical safety layer for processes that cannot afford ambiguity.</h2><div className="mt-7 space-y-3">{useCases.map(item => <article key={item.title} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-500" /><h3 className="text-sm font-bold text-slate-800 dark:text-slate-100">{item.title}</h3></div><p className="mt-2 pl-6 text-sm leading-6 text-slate-500 dark:text-slate-400">{item.text}</p></article>)}</div></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-slate-100 dark:border-slate-700 dark:bg-slate-800"><img src={productVisuals.recovery} alt="Conceptual visual of safe workflow retry and recovery" className="aspect-[4/3] w-full object-cover" /></div></div></section>
    <section className="bg-slate-950 py-20 text-white"><div className="mx-auto max-w-3xl px-5 text-center lg:px-8"><p className="text-[10px] font-bold tracking-[0.16em] text-blue-300">READY TO SEE THE RECORD BEHIND THE DECISION?</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-0.06em]">Start with a workflow you can explain.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-slate-300">Use your own account to start safely, or enter the prepared demonstration environment to explore approvals, retries, and recovery.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 bg-blue-600 px-6 font-bold hover:bg-blue-500"><a href="/login">Get Started <ArrowRight className="ml-2 size-4" /></a></Button><Button asChild size="lg" variant="outline" className="h-12 border-white/20 bg-white/10 px-6 font-bold text-white hover:bg-white/15 hover:text-white"><a href="/login?demo=1">Get a Demo</a></Button></div></div></section>
    <footer className="border-t border-slate-800 bg-slate-950 py-6 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 text-xs sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>FlowGuard by ForgeVI · Durable human-in-the-loop coordination.</span><span className="flex items-center gap-1.5"><Clock3 className="size-3.5 text-emerald-300" />Designed for visible work and safe decisions.</span></div></footer>
  </main>;
}
