/** FlowGuard Calm Operations Console: a recovery surface that makes uncertain system state actionable rather than silently failing. */
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CircleAlert, RefreshCcw, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/flowguard/AppShell";
import { PageHeader } from "@/components/flowguard/PageHeader";
import { StatusBadge } from "@/components/flowguard/StatusBadge";
import { useAuth } from "@/contexts/AuthContext";
import { flowguardApi, type WorkflowExecution } from "@/lib/flowguard-api";
import { toast } from "sonner";

export default function Recovery() {
  const { auth } = useAuth(); const [executions, setExecutions] = useState<WorkflowExecution[]>([]); const [loading, setLoading] = useState(false);
  const load = async () => { if (!auth) return; try { setExecutions(await flowguardApi.executions(auth.token)); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load recovery cases."); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 5_000); return () => clearInterval(timer); }, [auth]);
  const cases = useMemo(() => executions.filter(item => ["COMPENSATING", "MANUAL_RECOVERY_REQUIRED", "WAITING_FOR_APPROVAL", "RUNNING"].includes(item.status)), [executions]);
  const cancel = async (execution: WorkflowExecution) => { if (!auth) return; setLoading(true); try { await flowguardApi.cancel(auth.token, execution.id); toast.success("Compensation was started and every event was preserved."); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to begin recovery."); } finally { setLoading(false); } };
  return <AppShell><PageHeader eyebrow="RECOVERY CENTER" title="Resolve uncertainty without losing the trail." description="This view separates normal workflow work from cases that require compensation, reconciliation, or an authorized human decision." />
    <div className="rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(15,23,42,0.04)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><ShieldAlert className="size-4" /></div><div><p className="text-sm font-bold text-slate-800">Active recovery queue</p><p className="text-xs text-slate-500">Only authorized users can begin cancellation or compensation.</p></div></div><Button onClick={() => void load()} variant="ghost" size="sm" className="text-slate-600"><RefreshCcw className="mr-2 size-3.5" />Refresh</Button></div>{cases.length ? <div className="divide-y divide-slate-100">{cases.map(item => <div key={item.id} className="flex flex-col gap-4 px-5 py-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 font-mono text-[10px] font-bold text-slate-600">{item.businessKey.slice(-3)}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-slate-800">{item.businessKey}</p><StatusBadge status={item.status} /></div><p className="mt-1 truncate text-xs text-slate-500">At {item.currentStepKey.replaceAll("-", " ")} · {item.input.quantity} × {item.input.sku}</p></div></div><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><Link href={`/executions/${item.id}`}>Inspect trail <ArrowRight className="ml-2 size-3.5" /></Link></Button>{["RUNNING", "WAITING_FOR_APPROVAL"].includes(item.status) && <Button onClick={() => void cancel(item)} disabled={loading} size="sm" variant="outline" className="border-rose-200 text-rose-700 hover:bg-rose-50">Cancel & compensate</Button>}</div></div>)}</div> : <div className="p-12 text-center"><CircleAlert className="mx-auto size-7 text-emerald-500" /><p className="mt-4 font-bold text-slate-800">No active recovery cases</p><p className="mt-1 text-sm text-slate-500">Compensation and manual recovery work will be visible here when a workflow needs them.</p></div>}</div>
    <div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-700">1. Identify</p><p className="mt-2 text-xs leading-5 text-slate-500">The system persists failure context, external IDs, attempt count, and the last known state.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-700">2. Compensate</p><p className="mt-2 text-xs leading-5 text-slate-500">Completed actions are reversed in a safe business order using their own idempotency keys.</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-700">3. Escalate</p><p className="mt-2 text-xs leading-5 text-slate-500">A failed compensation becomes a visible manual-recovery case rather than an invisible error.</p></div></div>
  </AppShell>;
}
